steps:

- label: "Diffusion Model Test"
  timeout_in_minutes: 20
  agent_pool: mi325_2
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export GPU_ARCHS=gfx942
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - export VLLM_ROCM_USE_AITER=1
    - export VLLM_ROCM_USE_AITER_MHA=1
    - export VLLM_ROCM_USE_AITER_LINEAR=0
    - export VLLM_ROCM_USE_AITER_RMSNORM=0
    - pytest -s -v tests/e2e/offline_inference/test_t2i_model.py

- label: "Diffusion Cache Backend Test"
  timeout_in_minutes: 15
  agent_pool: mi325_1
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export GPU_ARCHS=gfx942
    - export VLLM_LOGGING_LEVEL=DEBUG
    - export VLLM_WORKER_MULTIPROC_METHOD=spawn
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - export VLLM_ROCM_USE_AITER=1
    - export VLLM_ROCM_USE_AITER_MHA=1
    - export VLLM_ROCM_USE_AITER_LINEAR=0
    - export VLLM_ROCM_USE_AITER_RMSNORM=0
    - pytest -s -v tests/e2e/offline_inference/test_cache_dit.py tests/e2e/offline_inference/test_teacache.py

- label: "Diffusion Parallelism Test"
  timeout_in_minutes: 15
  agent_pool: mi325_2
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - pytest -s -v tests/e2e/offline_inference/test_sequence_parallel.py

- label: "Diffusion GPU Worker Test"
  timeout_in_minutes: 20
  agent_pool: mi325_2
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - pytest -s -v tests/diffusion/test_diffusion_worker.py

- label: "Omni Model Test Qwen2-5-Omni"
  timeout_in_minutes: 15
  agent_pool: mi325_2
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export GPU_ARCHS=gfx942
    - export VLLM_LOGGING_LEVEL=DEBUG
    - export VLLM_WORKER_MULTIPROC_METHOD=spawn
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - export VLLM_ROCM_USE_AITER=1
    - export VLLM_ROCM_USE_AITER_MHA=1
    - export VLLM_ROCM_USE_AITER_LINEAR=0
    - export VLLM_ROCM_USE_AITER_RMSNORM=0
    - pytest -s -v tests/e2e/offline_inference/test_qwen2_5_omni.py

- label: "Omni Model Test Qwen3-Omni"
  timeout_in_minutes: 15
  agent_pool: mi325_2
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export VLLM_LOGGING_LEVEL=DEBUG
    - export VLLM_WORKER_MULTIPROC_METHOD=spawn
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - pytest -s -v tests/e2e/offline_inference/test_qwen3_omni.py tests/e2e/online_serving/test_qwen3_omni.py

- label: "Diffusion Image Edit Test"
  timeout_in_minutes: 15
  agent_pool: mi325_1
  depends_on: amd-build
  mirror_hardwares: [amdproduction]
  grade: Blocking
  commands:
    - export GPU_ARCHS=gfx942
    - export VLLM_LOGGING_LEVEL=DEBUG
    - export VLLM_WORKER_MULTIPROC_METHOD=spawn
    - export MIOPEN_DEBUG_CONV_DIRECT=0
    - export MIOPEN_DEBUG_CONV_GEMM=0
    - export VLLM_ROCM_USE_AITER=1
    - export VLLM_ROCM_USE_AITER_MHA=1
    - export VLLM_ROCM_USE_AITER_LINEAR=0
    - export VLLM_ROCM_USE_AITER_RMSNORM=0
    - pytest -s -v tests/e2e/online_serving/test_i2i_multi_image_input.py
